general:
  name: "mistral-7b-g5-2xl-ec2"      
  model_name: "mistral-7b-instruct"
 
aws:
  region: {region}
  sagemaker_execution_role: {role_arn}
  bucket: {write_bucket}

dir_paths:
    data_prefix: data
    prompts_prefix: prompts
    all_prompts_file: all_prompts.csv
    metrics_dir: metrics
    models_dir: models
    metadata_dir: metadata

s3_read_data:
    read_bucket: {read_bucket}
    scripts_prefix: scripts
    script_files:
    - hf_token.txt
    configs_prefix: configs
    config_files:
    - pricing.yml
    source_data_prefix: source_data
    source_data_files:
    - 2wikimqa_e.jsonl
    - 2wikimqa.jsonl
    - hotpotqa_e.jsonl
    - hotpotqa.jsonl
    - narrativeqa.jsonl
    - triviaqa_e.jsonl
    - triviaqa.jsonl
    tokenizer_prefix: mistral_tokenizer
    prompt_template_dir: prompt_template
    prompt_template_file: prompt_template_mistral.txt

## section that enables container to run notebooks and python scripts automatically 
run_steps:
  0_setup.ipynb: yes
  1_generate_data.ipynb: yes
  2_deploy_model.ipynb: yes
  3_run_inference.ipynb: yes
  4_model_metric_analysis.ipynb: yes
  5_cleanup.ipynb: yes

datasets:
  prompt_template_keys:
  - input
  - context

  filters:
  - language: en    
    min_length_in_tokens: 1
    max_length_in_tokens: 500
    payload_file: payload_en_1-500.jsonl
  - language: en
    min_length_in_tokens: 500
    max_length_in_tokens: 1000
    payload_file: payload_en_500-1000.jsonl
  - language: en
    min_length_in_tokens: 1000
    max_length_in_tokens: 2000
    payload_file: payload_en_1000-2000.jsonl
  - language: en
    min_length_in_tokens: 2000
    max_length_in_tokens: 3000
    payload_file: payload_en_2000-3000.jsonl
  - language: en
    min_length_in_tokens: 3000
    max_length_in_tokens: 3840
    payload_file: payload_en_3000-3840.jsonl

metrics:
  dataset_of_interest: en_3000-3840
  
pricing: pricing.yml
  
inference_parameters:
  ec2_djl:
    do_sample: yes
    temperature: 0.1
    top_p: 0.92
    top_k: 120  
    max_new_tokens: 100
    return_full_text: no

experiments:
  - name: "Mistral-7B-Instruct-v0.2"
    # AWS region, this parameter is templatized, no need to change
    region: {region}
    # model_id is interpreted in conjunction with the deployment_script, so if you
    # use a JumpStart model id then set the deployment_script to jumpstart.py.
    # if deploying directly from HuggingFace this would be a HuggingFace model id
    # see the DJL serving deployment script in the code repo for reference. 
    #from huggingface to grab
    model_id: mistralai/Mistral-7B-Instruct-v0.2 #model id, version and image uri not needed for byo endpoint
    model_version:
    model_name: "Mistral-7B-Instruct-v0.2"
    # this can be changed to the IP address of your specific EC2 instance where the model is hosted
    ep_name: 'http://127.0.0.1:8080/invocations' 
    instance_type: "g5.12xlarge"
    image_uri: 763104351884.dkr.ecr.{region}.amazonaws.com/djl-inference:0.29.0-lmi11.0.0-cu124
    deploy: yes #setting to yes to run deployment script for ec2
    instance_count: 
    deployment_script: ec2_deploy.py
    # FMBench comes packaged with multiple inference scripts, such as scripts for SageMaker
    # and Bedrock. You can also add your own. This is an example for a rest DJL predictor
    # for a llama3-8b-instruct deployed on ec2
    inference_script: ec2_predictor.py
    # This section defines the settings for Amazon EC2 instances
    ec2:
      # The following line specifies the runtime and Inferentia settings for the instance
      # '-u djl' tells the container to use the Deep Java Library (DJL) runtime
      # '--device /dev/neuron0 ... /dev/neuron5' specifies the Inferentia devices to be used
      gpu_or_neuron_setting: --runtime=nvidia --gpus all --shm-size 24g
      #This setting specifies the timeout (in seconds) for loading the model. 
      model_loading_timeout: 7200
    inference_spec:
      # this should match one of the sections in the inference_parameters section above
      parameter_set: ec2_djl
    # modify the serving properties to match your model and requirements
    serving.properties: |
      option.model_id=mistralai/Mistral-7B-Instruct-v0.2
    # runs are done for each combination of payload file and concurrency level
    payload_files:
    - payload_en_1-500.jsonl
    - payload_en_500-1000.jsonl
    - payload_en_1000-2000.jsonl
    - payload_en_2000-3000.jsonl
    - payload_en_3000-3840.jsonl
    # concurrency level refers to number of requests sent in parallel to an endpoint
    # the next set of requests is sent once responses for all concurrent requests have
    # been received.
    concurrency_levels:
    - 1
    - 2
    - 4
    - 8
    # Environment variables to be passed to the container
    # this is not a fixed list, you can add more parameters as applicable.
    env:

report:
  latency_budget: 5
  cost_per_10k_txn_budget: 100
  error_rate_budget: 0
  per_inference_request_file: per_inference_request_results.csv
  all_metrics_file: all_metrics.csv
  txn_count_for_showing_cost: 10000
  v_shift_w_single_instance: 0.025
  v_shift_w_gt_one_instance: 0.025  